### ISSUE TITLE
cache clear action fails in v0.21

### ISSUE THREAD

**Issue by pseyfert** [cherti/blinky#19]
running `blinky -Sc` throws the following error at me
```
Traceback (most recent call last):
  File "/home/pseyfert/.local/bin/blinky", line 253, in get_pkgname_with_meta
    *pkgnameparts, pkgver, pkgrel, pkgarch = fname.split(".pkg.")[0].split("-")
ValueError: not enough values to unpack (expected at least 3, got 1)

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/pseyfert/.local/bin/blinky", line 393, in <module>
    clean_cache(keep_installed=True)
  File "/home/pseyfert/.local/bin/blinky", line 297, in clean_cache
    prefixes_to_keep = [] if not keep_installed else get_installed_prefixes(ctx.cachedir)
  File "/home/pseyfert/.local/bin/blinky", line 269, in get_installed_prefixes
    name, version = get_pkgname_with_meta(p)
  File "/home/pseyfert/.local/bin/blinky", line 255, in get_pkgname_with_meta
    msg = "Non-package {} detected in {}. You might want to clean this up manually.".format(p, ctx.cachedir)
NameError: free variable 'p' referenced before assignment in enclosing scope
```

tried tags v0.20.1, v0.21, and master branch.

**Comment by pseyfert** [comment]
Applying the "obvious"[1] patches

```
diff --git a/scripts/blinky b/scripts/blinky
index 86375fb..5541b07 100644
--- a/scripts/blinky
+++ b/scripts/blinky
@@ -251,7 +251,7 @@ def clean_cache(keep_installed=False):
                try:
                        *pkgnameparts, pkgver, pkgrel, pkgarch = fname.split(".pkg.")[0].split("-")
                except ValueError:
-                       msg = "Non-package {} detected in {}. You might want to clean this up manually.".format(p, ctx.cachedir)
+                       msg = "Non-package {} detected in {}. You might want to clean this up manually.".format(fname, ctx.cachedir)
                        utils.logerr(None, msg)
                        raise
 
@@ -300,7 +300,10 @@ def clean_cache(keep_installed=False):
                if isin(p, prefixes_to_keep):
                        continue
                else:
-                       os.remove(p)
+                       try:
+                               os.remove(p)
+                       except IsADirectoryError:
+                               utils.logerr(None, "can't delete {} because it's a directory: {}".format(p, os.path.abspath(p)))
 
```
the clear action continues and finishes, but prints a bunch of errors
```
 !> Non-package logs detected in /home/pseyfert/.cache/blinky/pkg. You might want to clean this up manually.
 !> Non-package reviewed detected in /home/pseyfert/.cache/blinky/pkg. You might want to clean this up manually.
 !> Non-package pkg detected in /home/pseyfert/.cache/blinky/pkg. You might want to clean this up manually.
 !> Non-package build detected in /home/pseyfert/.cache/blinky/pkg. You might want to clean this up manually.
 !> can't delete logs because it's a directory: /home/pseyfert/.cache/blinky/pkg/logs
 !> can't delete reviewed because it's a directory: /home/pseyfert/.cache/blinky/pkg/reviewed
 !> can't delete pkg because it's a directory: /home/pseyfert/.cache/blinky/pkg/pkg
 !> can't delete build because it's a directory: /home/pseyfert/.cache/blinky/pkg/build
```


[1] what looks right when considering only the line where the exception occurs, not doing anything to the underlying problem but just letting the program continue.
